default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ga_development

test:
  <<: *default
  database: ga_test

production:
  <<: *default
  database: ga_production
  username: ga
  password: <%= ENV['GA_DATABASE_PASSWORD'] %>
